# Generated by Django 3.0.4 on 2020-04-03 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CragApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='search',
            options={'verbose_name_plural': 'Searches'},
        ),
    ]
